var dash=function(){var b={dbs:{},database:{},databases:{},store:{},stores:{},index:{},indexes:{},range:{},entry:{},entries:{},transaction:{},kr:window.IDBKeyRange,clone:function(a){var c={};if(b.isNumber(a))return parseInt(a,10);if(b.isArray(a))return a.slice(0);b.safeIterate(a,function(a,d){!b.isObject(d)||b.isFunction(d)||b.isArray(d)?c[a]=d:c[a]=b.clone(d)});return c},isEmpty:function(a){return b.isnt(a,void 0)&&b.isnt(a,null)&&b.isnt(a,"")&&(!b.isArray(a)||0<a.length)?!1:!0},exists:function(a){return b.isEmpty(a)?
!1:!0},contains:function(a,c,e){var d=!1;b.exists(a)&&b.safeIterate(a,function(a,h){if(b.is(e,!0)&&b.is(a,c)||b.is(h,c))d=!0});return d},is:function(a,b){return b===a},isnt:function(a,b){return b!==a},isObject:function(a){return b.isnt(a,null)&&b.isType("object",a)&&b.is("[object Object]",a.toString())},isString:function(a){return b.isType("string",a)},isFunction:function(a){return b.isType("function",a)},standardCallbackNames:"on_success on_error on_abort on_blocked on_upgrade_needed on_close on_complete".split(" "),
attribs:"auto_increment callback data database databases db duplicates entries entry event idx index index_key_path index_multi_entry index_unique indexes key multi_entry new_version objectstore old_version store store_key_path stores type unique version".split(" ")};b.attribs.push.apply(b.attribs,b.standardCallbackNames);b.results=function(a){var c={};b.safeEach(b.attribs,function(e,d){b.exists(a[d])&&(b.is(d,"db")?c[d]={name:a[d].name,version:a[d].version,objectStoreNames:a[d].objectStoreNames}:
b.is(d,"objectstore")?c[d]={name:a[d].name,indexNames:a[d].indexNames,autoIncrement:a[d].autoIncrement,keyPath:a[d].keyPath}:b.is(d,"idx")?c[d]={name:a[d].name,multiEntry:a[d].multiEntry,unique:a[d].unique,keyPath:a[d].keyPath}:c[d]=a[d])});return c};b.args=function(a){var c={};b.safeEach(b.attribs,function(e,d){b.exists(a[d])&&(c[d]=a[d])});return c};b.isArray=function(a){var b=!1;if(a instanceof Array||a instanceof DOMStringList)b=!0;return b};b.isNumber=function(a){return b.isType("number",a)||
b.is(isNaN(parseInt(a,10),!1))?!0:!1};b.isBoolean=function(a){return b.isType("boolean",a)||b.is(a,"true")||b.is(a,"false")?!0:!1};b.isType=function(a,c){return b.is(a,typeof c)};b.extend=function(a,c,e){a=a||{};b.safeIterate(b.clone(c),function(d,c){b.is(!0,e)&&b.isObject(c)?a[d]=b.extend({},c,e):a[d]=c});return a};b.safeIterate=function(a,b){for(var e in a)a.hasOwnProperty(e)&&b(e,a[e])};b.safeEach=function(a,c,e){var d,f=a.length;e=e||1;for(d=0;d<f;d+=e)b.safeApply(c,[d,a[d]])};b.safeApply=function(a,
c,e,d){if(b.isFunction(a))return a.apply(e||b,c||[]);if(b.isFunction(d))return b.safeApply(d,[])};b.safeEach(b.standardCallbackNames,function(a,c){b[c.replace(/^on_/g,"")]=function(a){b.safeApply(a[c],[a]);return a}});b.standardRequest=function(a){var c=a.request,e={};a=b.standardCallbacks(a);b.safeEach(b.standardCallbackNames,function(b,c){e[c.replace(/_/g,"")]=a[c]});a.request=b.extend(c,e);return a};b.standardCursor=function(a,c){var e=function(b){a.event=b;return a},d;a.direction=a.direction||
b.entries.next();a.range=a.range||b.range.get(a);a.entries=[];a.data=b.isFunction(a.data)?a.data():b.clone(a.data);b.isEmpty(a.transaction)&&(a.db=a.event.target.result,a.transaction=a.db.transaction([a.store],a.type));b.isEmpty(a.objectstore)&&(a.objectstore=a.transaction.objectStore(a.store));b.isEmpty(a.idx)&&!b.isEmpty(a.index)&&(a.idx=a.objectstore.index(a.index));d=b.isEmpty(a.index)?a.objectstore.openCursor(a.range,a.direction):a.idx.openCursor(a.range,a.direction);d.transaction.addEventListener("complete",
function(c){a.cursor=d.result;a=e(c);a.db.close();b.complete(a)});d.transaction.addEventListener("error",function(c){a.error=c;a=e(c);b.error(a)});d.addEventListener("success",function(f){a.cursor=d.result;a.entries=a.entries||[];a=e(f);b.safeApply(c,[a])})};b.standardCallbacks=function(a){var c={},e=function(e){a.event=e;a.transaction=a.request?a.request.transaction:e.target.transaction;b.exists(a.transaction)&&b.exists(a.transaction.db)&&(a.db=a.transaction.db);b.exists(e.newVersion)?(a.new_version=
e.newVersion,a.old_version=e.oldVersion,b.isnt(a.old_version,a.new_version)?a.upgrade=!0:a.upgrade=!1):a.upgrade=!1;return a};b.safeEach(b.standardCallbackNames,function(d,f){c[f]=function(){return function(c){b.safeApply(a[f],[e(c)])}}()});return c};b.transaction.read="readonly";b.transaction.readWrite="readwrite";b.transaction.versionChange="versionchange";b.database.close=function(a,c){a.db.close();b.isnt(c,!0)&&b.success(a)};b.database.remove=function(a,c){indexedDB.deleteDatabase(a.database);
b.isnt(c,!0)&&b.success(close_ctx)};b.database.get=function(a){var c=a.on_upgrade_needed,e=a.on_success,d=a.on_blocked,f=!1;a.request=b.isNumber(a.version)?indexedDB.open(a.database,a.version):indexedDB.open(a.database);a.db&&a.db.close();b.standardRequest(b.extend(a,{on_success:function(a){f||(a.upgrade=!1,a.opened=!0,a.on_success=e,a.db=a.event.target.result,b.success(a))},on_upgrade_needed:function(a){f=!0;a.upgrade=!0;a.opened=!0;a.on_upgrade_needed=c;b.upgrade_needed(a)},on_blocked:function(a){b.safeApply(d,
[a])}}))};b.databases.get=function(a){var c=a.on_success;if(!b.isFunction(indexedDB.webkitGetDatabaseNames))return b.error(a);a.request=indexedDB.webkitGetDatabaseNames();a.request.addEventListener("success",function(e){a.databases=e.target.result;a.on_success=c;b.success(a)})};b.store.clear=function(a){a.objectstore.clear();b.success(a)};b.store.remove=function(a){a.db.deleteObjectStore(a.store);b.success(a)};b.store.get=function(a){b.success(a)};b.stores.get=function(a){a.stores=a.db.objectStoreNames;
b.success(a)};b.index.get=function(a){a.idx=a.objectstore.index(a.index);b.success(a)};b.index.remove=function(a){a.objectstore.deleteIndex(a.index);b.success(a)};b.indexes.get=function(a){a.indexes=a.objectstore.indexNames;b.success(a)};b.entry.add=function(a){var c;a.data=b.isFunction(a.data)?a.data():b.clone(a.data);c=a.objectstore.add(a.data);a.transaction.addEventListener("error",function(e){a.error=e.target.error.message;b.error(a)});c.addEventListener("success",function(e){a.key=c.result;b.success(a)})};
b.entry.remove=function(a){var c,e=b.exists(a.range)||b.exists(a.upper)||b.exists(a.lower)||b.exists(a.only);a.data=b.isFunction(a.data)?a.data():b.clone(a.data);c=a.objectstore["delete"](e?a.range||b.range.get(a):a.key);a.transaction.addEventListener("complete",function(){a.entry=c.result;b.success(a)});a.transaction.addEventListener("error",function(e){a.error=e.target.error.message;b.error(a)})};b.entry.get=function(a){var c;a.data=b.isFunction(a.data)?a.data():b.clone(a.data);b.exists(a.index)?
(a.idx=a.objectstore.index(a.index),c=b.is(a.value,!1)?a.idx.getKey(a.key):a.idx.get(a.key)):c=a.objectstore.get(a.key);a.transaction.addEventListener("error",function(e){a.error=e.target.error.message;b.error(a)});c.addEventListener("success",function(e){a.entry=c.result;b.success(a)})};b.entry.put=function(a){var c;a.data=b.isFunction(a.data)?a.data():b.clone(a.data);c=b.exists(a.key)?a.objectstore.put(a.data,a.key):a.objectstore.put(a.data);a.transaction.addEventListener("complete",function(){a.key=
c.result;b.success(a)});a.transaction.addEventListener("error",function(e){a.error=e.target.error.message;b.error(a)})};b.entries.remove=function(a){a.type=b.transaction.readWrite;var c=a.on_success;b.standardCursor(a,function(a){a.entry=a.request;if(b.exists(a.cursor)&&(a.on_success=c,a.entry=a.cursor.value,a.entries=a.entries||[],a.entries.push(a.entry),a.cursor["delete"](),b.success(a),b.exists(a.cursor["continue"])))a.cursor["continue"]()})};b.entries.get=function(a){a.type=b.transaction.read;
var c=a.on_success;a.on_success=null;b.standardCursor(a,function(a){if(b.isnt(a.cursor,null)&&(a.on_success=c,a.entry=a.cursor.value,a.entries=a.entries||[],a.entries.push(a.entry),b.success(a),b.exists(a.cursor["continue"])))a.cursor["continue"]()})};b.entries.update=function(a){a.type=b.transaction.readWrite;var c=a.on_success;b.standardCursor(a,function(a){if(b.exists(a.cursor)&&(a.on_success=c,a.entry=a.cursor.value,a.entries=a.entries||[],a.entries.push(a.entry),a.cursor.update(a.data),b.success(a),
b.exists(a.cursor["continue"])))a.cursor["continue"]()})};b.range.get=function(a){var c=null,e=a.left_bound,d=a.right_bound,f=a.includes_left_bound,h=a.includes_right_bound;b.exists(e)&&b.exists(d)&&b.exists(f)&&b.exists(h)?c=b.kr.bound(e,d,f,h):b.exists(e)&&b.exists(f)?c=b.kr.lowerBound(e,f):b.exists(d)&&b.exists(h)?c=b.kr.upperBound(d,h):b.exists(a.value)&&(c=b.kr.only(a.value));a.result=c;b.success(a);return c};b.entries.next=function(a){return b.exists(a)&&b.is(!1,a.duplicates)?"nextunique":"next"};
b.entries.previous=function(a){return b.exists(a)&&b.is(!1,a.duplicates)?"prevunique":"prev"};b.deferred=function(){var a=!1,c=null,e=[],d=[],f=[],h=[],k=[];return{promise:function(l,g,n){var m=b.deferred();d.push(m);b.is(a,!0)?b.safeApply(c?l:g,e):b.safeEach([[h,l],[k,g],[f,n]],function(a,c){var d=c[1];b.isFunction(d)&&c[0].push(d)});return m.promise},resolve:function(){var f=arguments;b.is(a,!1)&&(a=c=!0,e=f,b.safeEach(h,function(a,c){b.safeApply(c,f)}),b.safeEach(d,function(a,c){b.safeApply(c.resolve,
f)}))},notify:function(){var a=arguments;b.safeEach(f,function(c,d){b.safeApply(d,a)});b.safeEach(d,function(c,d){b.safeApply(d.notify,a)})},reject:function(){var d=arguments;b.is(a,!1)&&(c=!1,a=!0,e=d,b.safeEach(k,function(a,c){b.safeApply(c,d)}))}}};b.transaction.queues=[];b.transaction.type=function(a){return b.contains(["add.index","remove.index","add.store","remove.store"],a)?b.transaction.versionChange:b.contains(["get.entry","get.entries"],a)?b.transaction.read:b.transaction.readWrite};b.detachContext=
function(a){return{database:a.database,store:a.store,version:null,store_key_path:a.store_key_path,unique:a.unique,multi_entry:a.multi_entry,data:a.data,auto_increment:a.auto_increment,on_complete:a.on_complete,key:a.key,index:a.index,index_key_path:a.index_key_path,index_multi_entry:a.index_multi_entry,index_unique:a.index_unique}};b.stage=function(a,c,e){var d=b.transaction.type(e),f=function(a,c){var d=b.detachContext(a);if(b.isEmpty(a.database))return b.safeApply(c,[a]);d.on_success=function(a){a.on_success=
null;a.version=a.db.version;a.db.close();b.safeApply(c,[a])};d.on_upgrade_needed=function(a){a.upgraded=!0;a.version=a.new_version;a.on_upgrade_needed=null;a.transaction.oncomplete=function(){a.db.close();b.safeApply(c,[a])}};b.database.get(d)},h=function(a,c){var f=b.detachContext(a);if(b.isEmpty(a.store)||b.contains(["add.store"],e))return b.safeApply(c,[a]);f.on_success=function(a){a.on_success=null;a.db=a.request.result;a.db.objectStoreNames.contains(a.store)?(b.isnt(a.transaction,null)&&(a.objectstore=
a.transaction.objectStore([a.store],d)),a.db.close(),b.safeApply(c,[a])):(a.version=a.db.version+1,a.on_success=null,a.on_upgrade_needed=function(a){a.on_upgrade_needed=null;a.transaction.addEventListener("complete",function(){a.db.close();b.safeApply(c,[a])});a.objectstore=a.db.createObjectStore(a.store,{keyPath:b.isString(a.store_key_path)?a.store_key_path:null,autoIncrement:b.isBoolean(a.auto_increment)?a.auto_increment:!1})},b.database.get(a))};f.version=null;b.database.get(f)},k=function(a,c){var d=
b.detachContext(a);if(b.isEmpty(a.store)||b.isEmpty(a.index)||b.contains("add.store get.store remove.store get.stores remove.stores remove.index add.index".split(" "),e))return b.safeApply(c,[a]);d.on_success=function(d){d.on_success=null;d.db=d.request.result;d.objectstore=d.db.transaction([d.store],b.transaction.read).objectStore(d.store);d.transaction=d.objectstore.transaction;if(d.objectstore.indexNames.contains(a.index))d.db.close(),b.safeApply(c,[d]);else{d.version=d.db.version+1;var e=function(a){a.transaction.addEventListener("complete",
function(){a.on_success=null;b.safeApply(c,[a]);a.db.close()});a.on_success=null;a.idx=a.objectstore.createIndex(a.index,a.index_key_path,{unique:a.index_unique||!1,multiEntry:a.index_multi_entry||!1})};d.on_success=null;d.on_upgrade_needed=function(a){a.objectstore=a.transaction.objectStore([a.store]);a.on_upgrade_needed=null;e(a)};d.db.close();b.database.get(d)}};b.database.get(d)},l=function(a){if(b.contains(["get.database","remove.database"],e))return g(a);var c=a.on_upgrade_needed,d=a.on_success;
a.on_success=null;a.on_upgrade_needed=null;f(a,function(a){h(a,function(a){k(a,function(a){a.on_success=d;a.on_upgrade_needed=c;g(a)})})})},g=function(c){var f=c.on_success,h=c.on_complete,g=b.detachContext(c),k=function(c){b.exists(c.store)&&b.isnt(d,b.transaction.versionChange)?(b.is(c.transaction,null)&&(c.transaction=c.db.transaction([c.store],d)),c.objectstore=c.transaction.objectStore(c.store),c.transaction.addEventListener("complete",function(){c.db.close()})):b.exists(c.store)&&(c.db=c.request.result,
c.transaction=c.request.transaction,b.is(c.transaction,null)&&(c.transaction=c.db.transaction([c.store],d)),b.contains(["add.store","remove.store"],e)||(c.objectstore=c.transaction.objectStore(c.store)),c.transaction.addEventListener("complete",function(){c.db.close()}));c.on_success=function(a){a=b.results(a);a.on_success=f;b.success(a)};c.on_complete=function(a){a=b.results(a);a.on_complete=h;b.safeApply(a.on_complete,[a])};b.safeApply(a,[c])};g.version=c.version;if(b.contains(["get.databases",
"remove.database","get.database"],e))return b.safeApply(a,[c]);b.isnt(b.transaction.versionChange,d)?g.on_success=k:(g.version=c.db.version+1,g.on_upgrade_needed=k);b.database.get(g)};c=b.args(c);c.type=d;b.transaction.queues.push(c);(function(){var a=b.transaction.queues.shift();b.isnt(a,null)&&l(a)})()};b.wrap=function(a,c){return function(e){e=e||{};var d={};b.safeEach(b.standardCallbackNames,function(a,b){d[b.replace(/^on_/,"")]=e[b]});return function(a,d,e,l){var g=b.deferred(),n=b.contains(["get.entries",
"update.entries","remove.entries"],c),m={success:"s",error:"e",abort:"a",complete:"c",upgrade_needed:"u",blocked:"b",closed:"l"};b.safeIterate(d,function(c,e){a["on_"+c]=function(a,c){return function(d){b.isObject(d)&&b.safeIterate(c,function(a,c){var e="on_"+a;b.isFunction(c)?d[e]=c:delete d[e]});d=b.args(d);var e;e=b.is(a,"s")?n?g.notify:g.resolve:b.is(a,"e")||b.is(a,"a")||b.is(a,"b")?g.reject:g.resolve;b.safeApply(e,[d],g)}}(m[c],d)});try{b.stage(e,a,l)}catch(p){a.error=p}return g.promise}(e,d,
a,c)}};return function(a){var c={},e=[],d;b.safeIterate(a,function(a,h){e=a.split(".");d=e[0];c[d]=c[d]||{};c[d][e[1]]=b.wrap(h,a)});return c}({"add.entry":b.entry.add,"get.database":b.database.get,"get.databases":b.databases.get,"get.store":b.store.get,"get.stores":b.stores.get,"get.index":b.index.get,"get.indexes":b.indexes.get,"get.entry":b.entry.get,"get.entries":b.entries.get,"update.entries":b.entries.update,"put.entry":b.entry.put,"clear.store":b.store.clear,"remove.database":b.database.remove,
"remove.store":b.store.remove,"remove.index":b.index.remove,"remove.entry":b.entry.remove,"remove.entries":b.entries.remove})}();