(function(){var l=window,b={s:{},c:{},O:{},f:{},T:{},index:{},R:{},j:{},ua:{},cursor:{},transaction:{},db:l.indexedDB,ya:l.IDBTransaction,K:l.IDBCursor,L:l.IDBKeyRange,J:function(a){var d={};if(b.C(a))return parseInt(a,10);if(b.isArray(a))return a.slice(0);b.n(a,function(a,e){!b.D(e)||b.l(e)||b.isArray(e)?d[a]=e:d[a]=b.J(e)});return d},o:function(a){return b.A(a,void 0)&&b.A(a,null)&&b.A(a,"")&&(!b.isArray(a)||0<a.length)?!1:!0},a:function(a){return b.o(a)?!1:!0},contains:function(a,d,c){var e=!1;
b.a(a)&&b.n(a,function(a,g){if(b.d(c,!0)&&b.d(a,d)||b.d(g,d))e=!0});return e},t:function(a,d){var c=d.split("."),e=c.shift();if(b.o(a))return!1;for(;e;){if(b.o(a[e]))return!1;a=a[e];e=c.shift()}return!0},ka:function(a,d){for(var c=d.split("."),e=c.shift(),f;e;)b.a(a[e])&&(f=a[e]),a=a[e],e=c.shift();return f},d:function(a,b){return b===a},A:function(a,b){return b!==a},D:function(a){return b.F("object",a)&&b.d("[object Object]",a.toString())},oa:function(a){return b.F("string",a)},l:function(a){return b.F("function",
a)},isArray:function(a){return a instanceof Array||a instanceof DOMStringList},ha:function(a){a=parseInt(a,10);return b.d(!1,b.C(a))?null:a},C:function(a){return b.F("number",a)||b.d(isNaN(parseInt(a,10),!1))},na:function(a){return b.d(a,null)},pa:function(a){return b.d(a,void 0)},$:function(a){return b.F("boolean",a)||b.d(a,"true")||b.d(a,"false")},F:function(a,d){return b.d(a,typeof d)},extend:function(a,d,c){b.n(b.J(d),function(d,f){a[d]=b.d(!0,c)&&b.D(f)?b.extend({},f,c):f});return a},n:function(a,
b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])},r:function(a,d,c){var e=a.length,f=1;!0===c&&(f=-f);for(c=0;c<e;c+=f)b.b(d,[c,a[c]])},fa:function(a,d,c){var e=[];b.isArray(a)?b.r(a,function(){e.push(b.b(d,arguments))}):b.D(a)&&b.n(a,function(){e.push(b.b(d,arguments))});b.b(c,[e]);return e},wa:function(a,d,c,e){var f=[];b.isArray(a)?b.r(a,function(a,c){f.push(b.b(b.l(c)?c:e,d))}):b.D(a)?b.n(a,function(a,c){f.push(b.b(b.l(c)?c:e,d))}):f=[];b.b(c,[f]);return f},b:function(a,d,c,e){if(b.l(a))return a.apply(c||
b,d||[]);if(b.l(e))return b.b(e,[])},k:function(a){b.b(a.g,[a]);return a},error:function(a){b.b(a.q,[a]);return a},complete:function(a){b.b(a.N,[a]);return a},abort:function(a){b.b(a.H,[a]);return a},m:function(a){b.b(a.i,[a]);return a},ga:["on_success","on_error","on_abort","on_blocked","on_upgrade_needed"],v:function(a){var d=a.h;a=b.X(a);if(b.a(d)&&b.d(d.readyState,"done"))return a.result=b.object.result(a),b.k(a);b.extend(d,{onsuccess:a.g,onerror:a.q,onabort:a.H,onclose:a.sa,onblocked:a.M,onupgradeneeded:a.i});
a.h=d;return a},X:function(a){function d(c){a.event=c;b.t(c,"target.transaction")&&(a.transaction=c.target.transaction,a.db=a.transaction.db);a.result=b.object.result(a);return a}var c={};b.r(b.ga,function(e,f){c[f]=function(){return function(c){b.b(a[f],[d(c)])}}()});return c}};b.c.close=function(a){a.db=b.c.get(a);b.a(a.db)&&(b.b(a.db.close,[]),delete b.s[a.c]);b.k(a)};b.c.set=function(a){return b.s[a.c]=a.db};b.c.get=function(a){return b.a(a.db)?a.db:b.s[a.c]};b.c.m=function(a){function d(d){b.a(d.f)&&
(d.e=d.db.objectStore(a.f));d.g=c;b.b(c,[d])}var c=a.g;a.db=b.c.get(a);a.version=b.ha(a.version);b.o(a.db)?b.c.open(b.extend(a,{i:d(a),g:d(a)})):(a.version=a.version||a.db.version+1,a.type=b.transaction.ia,a.transaction=b.transaction.create(a),d(a))};b.c.open=function(a){var d=[a.c],c=a.i,e=a.g;a.db=a.db||b.c.get(a);b.a(a.version)&&d.push(a.version);b.a(a.db)&&(a.error="database already open",b.error(a));a.h=b.b(a.db.open,d,a.db);b.v(b.extend(a,{g:function(a){a.m=!1;a.db=a.result;delete a.result;
a.k=e;b.k(a)},i:function(a){a.m=!0;a.db=a.result;delete a.result;a.i=c;b.m(a)}}))};b.c.get=function(a){var d=a.c,c=a.g;b.a(b.s[d])?(a.db=b.s[d],b.k(a)):b.c.open(b.extend(a,{g:function(a){a.db=a.result;delete a.result;a.g=c;b.k(a)}}))};b.O.get=function(a){var d=a.g;a.h=b.db.za();return b.v(b.extend(a,{g:function(a){a.O=a.result;delete a.result;a.g=d;b.k(a)}}))};b.f.clear=function(a){a.transaction=b.transaction.create(a);a.db=a.transaction.db;a.e=a.transaction.objectStore(a.f);a.h=a.e.clear();b.v(a);
return a};b.f["delete"]=function(a){var d=a.g;b.c.m(b.extend(a,b.X({i:function(c){try{a.h=a.db.deleteObjectStore(a.f),c.g=d,b.k(c)}catch(e){a.error=e,b.error(a)}}})));return a};b.f.create=function(a){var d=a.i;b.c.m(b.extend(b.v(a,{i:function(c){try{return c.e=c.db.createObjectStore(c.f,{keyPath:b.o(a.U)?null:a.U,autoIncrement:b.$(a.Y)?a.Y:!1}),c.i=d,b.m(c)}catch(e){return c.error=e,b.error(c)}}})))};b.f.get=function(a){a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);return b.k(a)};
b.T.get=function(a){a.db=a.db||b.s[a.c];a.T=a.db.objectStoreNames;return b.k(a)};b.index.create=function(a){var d=a.i;a.i=function(c){c.db=b.c.set(c);c.e=c.transaction.objectStore(a.f);try{c.u=c.e.createIndex(c.index,c.U,{unique:c.unique||!1,multiEntry:c.ra||!1}),c.i=d,b.m(c)}catch(e){c.error=e,b.error(c)}};b.c.m(a)};b.index.get=function(a){a.db=a.db||b.s[a.c];a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);a.u=a.e.index(a.index);b.k(a);return a};b.index["delete"]=function(a){var d=
a.i;a.i=function(c){c.i=d;try{c.h=c.e.deleteIndex(a.index),b.k(c)}catch(e){c.error=e,b.error(c)}};b.c.m(a)};b.R.get=function(a){a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);a.R=a.e.indexNames;b.k(a);return a};b.transaction.ca="readonly";b.transaction.da="readwrite";b.transaction.ia="versionchange";b.transaction.create=function(a){a.db=a.db||b.s[a.c];a.type=a.type||b.transaction.da;a.result=a.db.transaction([a.f],a.type);return a.result};b.object.add=function(a){a.data=
b.l(a.data)?a.data():b.J(a.data);a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);a.h=a.e.add(a.data);return b.v(a)};b.object["delete"]=function(a){a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);a.h=a.e["delete"](a.key);return b.v(a)};b.object.get=function(a){var d=b.a(a.j)||b.a(a.upper)||b.a(a.lower)||b.a(a.only);a.key=d?a.j||b.j.get(a):a.key;a.type=a.type||b.transaction.ca;a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);
if(b.a(a.index))try{a.u=a.e.index(a.index),a.h=b.d(a.value,!1)?a.u.getKey(a.key):a.u.get(a.key)}catch(c){return a.error=c,b.error(a)}else a.h=a.e.get(a.key);return b.v(a)};b.object.put=function(a){a.data=b.l(a.data)?a.data():a.data;a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);a.h=b.a(a.key)?a.e.put(a.data,a.key):a.e.put(a.data);return b.v(a)};b.object.result=function(a){a=a.event;var d=null;b.t(a,"target.result.value")?d=a.target.result.value:b.t(a,"target.result")?d=a.target.result:
b.t(a,"result")?d=a.result:b.t(a,"request.result")&&(d=a.h.result);return d};b.p["delete"]=function(a){function d(b){a.event=b;return a}var c=0,e=a.q,f=a.g;a.direction=a.direction||b.p.next();a.j=a.j||b.j.get(a);a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);try{b.o(a.index)?a.h=a.e.openCursor(a.j,a.direction):(a.u=a.e.index(a.index),a.h=a.u.openCursor(a.j,a.direction)),b.extend(a.h,{onsuccess:function(d){var g={event:d};a.w=!1;a.cursor=b.object.result(g);a.result=b.object.result(g);
a.event=d;b.a(a.B)&&b.n(a.B,function(c,d){var e=b.t(a.result,c)?a.result[c]:null;b.l(a.Q)&&(a.Q=d(e));b.a(e)&&b.a(a.Q)&&b.A(e,a.Q)&&(a.w=!0)});if(b.d(a.w,!1)&&b.a(a.cursor)&&b.a(a.result))if(b.a(a.S))try{a.cursor.advance(a.S)}catch(k){a.error=k,b.error(a)}else try{b.extend(a.cursor["delete"](),{onsuccess:function(d){c+=1;if(b.C(a.G)&&c>=a.G)b.complete(a);else if(b.a(a.cursor))if(b.a(a.I))try{a.cursor.advance(a.I)}catch(e){a.error=e,b.error(a)}else if(b.l(a.cursor["continue"]))try{a.cursor["continue"]()}catch(m){a.error=
m,b.error(a)}d.g=f;b.k(d)},onerror:function(){a.q=e;b.error(a)}})}catch(m){a.error=m,b.error(a)}else b.error(a)},onerror:function(a){b.error(d(a))},onabort:function(a){b.abort(d(a))}})}catch(g){a.error=g,b.error(a)}};b.p.get=function(a){function d(b){a.event=b;return a}var c=0;a.j=a.j||b.j.get(a);a.transaction=b.transaction.create(a);try{b.o(a.index)?a.h=a.transaction.openCursor(a.aa,a.direction):a.h=a.transaction.index(a.index).openCursor(a.aa,a.direction),b.extend(a.h,{onsuccess:function(d){a.event=
d;a.cursor=b.object.result(a);a.result=b.object.result(a);b.a(a.B)&&b.n(a.B,function(c,d){var e=b.t(a.result,c)?a.result[c]:null;b.l(d)&&(d=d(e));b.a(e)&&b.a(d)&&b.A(e,d)&&(a.w=!0)});if(b.d(a.w,!0)||b.o(a.cursor))b.error(a);else if(b.a(a.S))try{a.cursor.advance(a.S)}catch(e){a.error=e,b.error(a)}else if(b.k(a),c+=1,b.C(a.G)&&c>=a.G)b.complete(a);else if(b.a(a.cursor))if(b.a(a.I))try{a.cursor.advance(a.I)}catch(h){a.error=h,b.error(a)}else if(b.l(a.cursor["continue"]))try{a.cursor["continue"]()}catch(n){a.error=
n,b.error(a)}},onerror:function(a){return b.error(d(a))},onabort:function(a){return b.abort(d(a))}})}catch(e){return a.error=e,b.error(a)}};b.p.update=function(a){function d(b){a.event=b;return a}var c=0,e=a.g,f=a.q;a.direction=a.direction||b.p.next();a.j=a.j||b.j.get(a);a.transaction=b.transaction.create(a);a.e=a.transaction.objectStore(a.f);a.data=b.l(a.data)?a.data():b.J(a.data);try{b.o(a.index)?a.h=a.e.openCursor(a.j,a.direction):(a.u=a.e.index(a.index),a.h=a.u.openCursor(a.j,a.direction)),b.extend(a.h,
{onsuccess:function(d){a.cursor=d.target.result;a.result=d.target.result.value;a.w=!1;a.event=d;b.a(a.B)&&b.n(a.B,function(c,d){var e=b.t(a.result,c)?a.result[c]:null;b.l(d)&&(d=d(e));b.a(e)&&b.a(d)&&b.A(e,d)&&(a.w=!0)});if(b.d(a.w,!1)&&b.a(a.cursor)&&b.a(a.result)){a.data=b.d(a.replace,!0)?a.result:b.extend(a.result,a.data);try{b.extend(a.cursor.update(a.data),{onsuccess:function(){c+=1;if(b.C(a.G)&&c>=a.G)b.complete(a);else if(b.a(a.cursor))if(b.a(a.I))try{a.cursor.advance(a.I)}catch(d){a.error=
d,b.error(a)}else if(b.l(a.cursor["continue"]))try{a.cursor["continue"]()}catch(f){a.result=f,b.complete(a)}a.g=e;return b.k(a)},onerror:function(){a.q=f;return b.error(a)}})}catch(g){return a.error=g,b.error(a)}}else return b.error(a)},onerror:function(a){return b.error(d(a))},onabort:function(a){return b.abort(d(a))}})}catch(g){return a.error=g,b.error(a)}};b.j.get=function(a){var d=null,c=a.qa,e=a.va,f=a.la,g=a.ma;b.a(c)&&b.a(e)&&b.a(f)&&b.a(g)?d=b.L.bound(c,e,f,g):b.a(c)&&b.a(f)?d=b.L.lowerBound(c,
f):b.a(e)&&b.a(g)?d=b.L.upperBound(e,g):b.a(a.value)&&(d=b.L.only(a.value));a.result=d;b.k(a);return d};b.p.next=function(a){return b.d(!1,a.Z)?b.K.NEXT_NO_DUPLICATE:b.K.NEXT};b.p.ta=function(a){return b.d(!1,a.Z)?b.K.PREV_NO_DUPLICATE:b.K.PREV};b.P=function(){function a(a){b.n(k,function(c){b.b(c,a)})}var d=!1,c=null,e=[],f=[],g=[],h=[],n=[],k=[];return{V:{xa:function(a,p,q){var k=b.P();f.push(k);b.d(d,!0)?b.b(c?a:p,e):b.r([[h,a],[n,p],[g,q]],function(a,c){var d=c[1];b.l(d)&&c[0].push(d)});return k.V},
"finally":function(a){b.d(d,!1)?k.push(a):b.b(a,e)}},W:function(){var g=arguments;c=!0;e=g;b.d(d,!1)&&(d=!0,b.r(h,function(a,c){b.b(c,g)}),b.r(f,function(a,c){b.b(c.W,g)}),a(g))},ba:function(){var a=arguments;b.d(d,!1)&&b.r(g,function(c,d){b.b(d,a)})},ea:function(){var f=arguments;c=!1;e=f;b.d(d,!1)&&(d=!0,b.r(n,function(a,c){b.b(c,f)}),a(f))}}};b.ja=function(a,d){return function(c){function e(a,c){var d=[];a=f(a);switch(c){case "s":d.push(m?k:n);break;case "e":d.push(h);break;case "a":d.push(h);
break;case "c":d.push(m?n:k);break;case "u":d.push(k);break;case "b":d.push(h)}b.r(d,function(c,d){b.b(d,a)})}function f(a){var c=a[0];b.D(c)&&(b.a(p)?c.g=p:delete c.g,b.a(q)?c.q=q:delete c.q,b.a(l)?c.H=l:delete c.H,b.a(r)?c.N=r:delete c.N,b.a(t)?c.M=t:delete c.M,b.a(s)?c.i=s:delete c.i,delete c.event);a[0]=c;return a}c=c||{};var g=b.P(),h=g.ea,n=g.W,k=g.ba,m=b.contains(["indexes.create","stores.create"],d),p=null,q=null,l=null,r=null,s=null,t=null,p=c.g,q=c.q,l=c.H,r=c.N,s=c.i,t=c.M;b.d(m,!1)&&b.d(d.split(".")[0],
"record")&&(m=b.a(c.index));a(b.extend(c,{g:function(){e(arguments,"s");b.b(p,arguments)},q:function(){e(arguments,"e");b.b(q,arguments)},H:function(){e(arguments,"a");b.b(l,arguments)},N:function(){e(arguments,"c");b.b(r,arguments)},i:function(){e(arguments,"u");b.b(s,arguments)},M:function(){e(arguments,"b");b.b(t,arguments)}}));return g.V}};return function(a){var d={},c=[],e,f=/^_/;b.n(a,function(a,h){c=a.split(".");b.A(c[0].match(f),null)?(e=c[0].replace(f,""),d[e]=d[e]||{},d[e][c[1]]=h):(e=c[0],
d[e]=d[e]||{},d[e][c[1]]=b.ja(h,a))});return d}({"close.database":b.c.close,"open.database":b.c.open,"remove.database":b.c["delete"],"get.database":b.c.get,"upgrade.database":b.c.m,"get.databases":b.O.get,"create.store":b.f.create,"clear.store":b.f.clear,"get.store":b.f.get,"remove.store":b.f["delete"],"get.stores":b.T.get,"create.index":b.index.create,"get.index":b.index.get,"remove.index":b.index["delete"],"get.indexes":b.R.get,"add.object":b.object.add,"remove.object":b.object["delete"],"get.object":b.object.get,
"put.object":b.object.put,"remove.objects":b.p["delete"],"get.objects":b.p.get,"update.objects":b.p.update,each:b.fa,extend:b.extend,defer:b.P})})();