# https://github.com/di-sukharev/opencommit
name: 'Commit Reshaping'

on:
  push:
    branches-ignore: [main dev development release]

jobs:
  opencommit:
    timeout-minutes: 5
    name: Commit Reshaping (OpenCommit)
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: di-sukharev/opencommit@github-action-v1.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          OCO_OPENAI_MAX_TOKENS: 500
          OCO_OPENAI_API_KEY: ${{ secrets.OCO_OPENAI_API_KEY }}
          OCO_OPENAI_BASE_PATH: ''
          OCO_DESCRIPTION: false
          OCO_EMOJI: true
          OCO_MODEL: gpt-4
          OCO_LANGUAGE: en
          OCO_MESSAGE_TEMPLATE_PLACEHOLDER: '$msg'
